### ISSUE TITLE
docklocation_z = ?

### ISSUE THREAD

**Issue by bjoern79de** [tronfu/Voron-2-Mods#1]
It would be nice, if docklocation_z could be determined automaticly (by using the actual probe-attachment as a second z-endstop). One of the main advantages of klicky-probe is to use it together with klipper_z_calibration, to be able to replace nozzles/printheads without any reconfigurations. I have height-differences of up to 10mm between my printheads - so I would have to reconfigure the docklocation_z instead of z-offset every time.

**Comment by tronfu** [comment]
Thanks for the suggestion. Is this a problem only with the servo-dock or also with the stock gantry-mounted dock?

**Comment by bjoern79de** [comment]
Only with a non-gantry-mounted dock. With gantry-mounted docks, the z-location is not relevant.

**Comment by tronfu** [comment]
Understood. When you say using the actual probe-attachment as a second z-endstop, what exactly are you envisioning? Can you visually illustrate that for me?

**Comment by bjoern79de** [comment]
I meant that the A/B-Mount could be moved to the x/y-position in a safe distance over the probe and then moved down (step by step) until the contact is established.

**Comment by tronfu** [comment]
This functionality has been added. See the latest README.
